esphome:
  name: thermostat
  friendly_name: Thermostat
  platformio_options:
    board_build.flash_mode: dio
  # Optionally, if you need BLE
  # https://github.com/esphome/issues/issues/2941#issuecomment-1331851692
  on_boot:
    - priority: 500
      then:
        - esp32_ble_tracker.stop_scan:
    - priority: 100
      then:
        - delay: 10s
        - esp32_ble_tracker.start_scan:
            continuous: true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"    
      variant: ESP32C3

logger:
  baud_rate: 0
  level: DEBUG

api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

wifi:
  output_power: "8.5" # Sometimes causes a boot loop without it

  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Thermostat"
    password: "abcd1234"

captive_portal:


# Optionally, if you need BLE
esp32_ble_tracker:
  scan_parameters:
    continuous: false
    interval: 211ms
    window: 120ms
    active: true

bluetooth_proxy:
  active: true



uart:
  baud_rate: 9600
  tx_pin: GPIO21 
  rx_pin: GPIO20

time:
  - platform: homeassistant
    id: ha_time

tuya:
  time_id: ha_time


climate:
  - platform: tuya
    # The device itself has a step of 0.5, but it works OK with a 0.1 step
    name: "Climate"
    switch_datapoint: 1
    target_temperature_datapoint: 2
    current_temperature_datapoint: 3
    temperature_multiplier: 0.1
    active_state:
      datapoint: 5
    # optional
    #visual:
    #  min_temperature: 5
    #  max_temperature: 60 # depends on the upper limit value (default: 60), max is 95


sensor:
  - platform: "tuya"
    # Only retrieves Error 1 when an external sensor is set without being connected
    # There may be more error codes, it's a bitmask type
    # 0 - OK, no error
    name: "Error"
    sensor_datapoint: 11
    entity_category: diagnostic
  

switch:
  - platform: "tuya"
    name: "Child lock"
    switch_datapoint: 9
  - platform: "tuya"
    name: "Antifreeze"
    switch_datapoint: 103
    entity_category: config
    disabled_by_default: true
  - platform: "tuya"
    # If enabled, the relay will close when it shouldn't heat and vice versa, inverting the relay's output state
    # Useful for NO/NC contacts
    name: "Invert output"
    switch_datapoint: 108
    entity_category: config
    disabled_by_default: true
  - platform: "tuya"
    name: "Beeper"
    switch_datapoint: 109
    entity_category: config


select:
  - platform: "tuya"
    name: "Screen brightness"
    enum_datapoint: 106
    options:
      0: "Off"
      1: "Low"
      2: "Medium"
      3: "High"
    entity_category: config
  - platform: "tuya"
    # As mentioned in the manual
    # it seems to be for schedule mode, which this thermostat model doesn't support
    # (at least from the thermostat itself) 
    name: "Rest day"
    enum_datapoint: 107
    options:
      0: "Off"
      1: "5 - Two day weekend"
      2: "6 - Signle dayoff"
      3: "7 - No rest"
    entity_category: config
    disabled_by_default: true
  - platform: "tuya"
    # There is no separate datapoint for each sensor type; it changes the value in datapoint 3
    name: "Sensor"
    enum_datapoint: 110
    options:
      0: "Internal"
      1: "External"
      2: "All" # Maybe it takes the average between internal and external
    entity_category: config


number:
  - platform: "tuya"
    name: "Upper limit"
    number_datapoint: 15
    min_value: 15
    max_value: 95
    step: 1
    device_class: temperature
    unit_of_measurement: "째C"
    entity_category: config
    disabled_by_default: true
  - platform: "tuya"
    # Corrects the value of datapoint 3, which is the temperature sensor. Works for each sensor type
    name: "Correction"
    number_datapoint: 19
    min_value: -9.9
    max_value: 9.9
    step: 0.1
    multiply: 10
    device_class: temperature
    unit_of_measurement: "째C"
    entity_category: config
  - platform: "tuya"
    # On the device, the minimum value is 0.5 and the step is 0.5, but it also works with 0.1 value and step
    name: "Hysteresis"
    number_datapoint: 101
    min_value: 0.1
    max_value: 10
    step: 0.1
    multiply: 10
    device_class: temperature
    unit_of_measurement: "째C"
    entity_category: config
  - platform: "tuya"
    name: "Limit"
    number_datapoint: 102
    min_value: 35
    max_value: 60
    step: 1
    device_class: temperature
    unit_of_measurement: "째C"
    entity_category: config
    disabled_by_default: true
